#!/bin/bash

echo ""
echo "This script copies a udev rule for ftd2xx devices and epos4 HID driver"
echo ""

sudo cp `rospack find epos4_control`/99-epos4.rules /etc/udev/rules.d
sudo cp `rospack find epos4_control`/99-ftdi.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
